# Comment è¯„è®ºç›¸å…³
disqus: ## scarsu ## Disqusè¯„è®º Your disqus_shortname, e.g. username
uyan: ## Your uyan_id. e.g. 1234567
livere: ## Your livere data-uid, e.g. MTAyMC8zMDAxOC78NTgz
changyan: ## Your changyan appid, e.g. cyrALsXc8
changyan_conf: ## Your changyan conf, e.g. prod_d8a508c2825ab57eeb43e7c69bba0e8b
# Gitment
# Introduction: https://imsun.net/posts/gitment-introduction/
gitment:
    enable: false ## If you want to use Gitment comment system please set the value to true.
    owner: scarsu ## Your GitHub ID, e.g. username
    repo: ScarSuHexo_Netlify ## The repository to store your comments, make sure you're the repo's owner, e.g. imsun.github.io
    client_id: d6f2352e58fb923322f5 ## GitHub client ID, e.g. 75752dafe7907a897619
    client_secret: de27abd6cce5329c72ef8a7fb7cc91cec332cc89 ## GitHub client secret, e.g. ec2fb9054972c891289640354993b662f4cccc50
gitalk:
    enable: false ## If you want to use Gitment comment system please set the value to true.
    owner: scarsu ## Your GitHub ID, e.g. username
    repo: ScarSuHexo_Netlify ## The repository to store your comments, make sure you're the repo's owner, e.g. gitalk.github.io
    client_id: d6f2352e58fb923322f5 ## GitHub client ID, e.g. 75752dafe7907a897619
    client_secret: de27abd6cce5329c72ef8a7fb7cc91cec332cc89 ## GitHub client secret, e.g. ec2fb9054972c891289640354993b662f4cccc50
    admin: scarsu ## Github repo owner and collaborators, only these guys can initialize github issues.
valine: ## https://valine.js.org
    enable: true ## If you want to use Valine comment system, please set the value to true.
    appid: 6mzkhc3s2KpjnioquLiNngGi-gzGzoHsz ## Your LeanCloud application App ID, e.g. pRBBL2JR4N7kLEGojrF0MsSs-gzGzoHsz
    appkey: BUMKR7vOFUL0PVOCEI3AApDe ## Your LeanCloud application App Key, e.g. tjczHpDfhjYDSYddzymYK1JJ
    notify: false ## Mail notifier, see https://github.com/xCss/Valine/wiki/Valine-è¯„è®ºç³»ç»Ÿä¸­çš„é‚®ä»¶æé†’è®¾ç½®
    verify: true ## Validation code.
    placeholder: æ¬¢è¿ç•™è¨€ï¼ŒæœŸå¾…å›å¤è¯·ç•™ä¸‹é‚®ç®± ## Comment box placeholders.
    avatar: "identicon" ## Gravatar type, see https://github.com/xCss/Valine/wiki/avatar-setting-for-valine
    pageSize: 10 ## Number of comments per page.
    guest_info: nick,mail,link ## Attributes of reviewers.
    visitor: true  #é˜…è¯»é‡ç»Ÿè®¡
    comment_count: true # if false, comment count will only be displayed in post page, not in home page

leancloud_visitors:
  enable: false

# search æœç´¢ç›¸å…³
google_search: false ## Use Google search, true/false.
baidu_search: false ## Use Baidu search, true/false.
swiftype: ## Your swiftype_key swiftç«™å†…æœç´¢key, e.g. m7b11ZrsT8Me7gzApciT
tinysou: ## Your tinysou_key ä¸ºæœç´¢key, e.g. 4ac092ad8d749fdc6293
self_search: true ## Use a jQuery-based local search engine, true/false.

# website analytics ç½‘ç«™ç»Ÿè®¡
google_analytics: UA-175312250-1 ## Your Google Analytics tracking id, e.g. UA-42425684-2
baidu_analytics: 652643ccce8310366e3ea65528fb9290 ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
busuanzi: false ## æ˜¯å¦ä½¿ç”¨ä¸è’œå­é¡µé¢è®¿é—®è®¡æ•° If you want to use Busuanzi page views please set the value to true.

# others å…¶ä»–
fancybox: true ## æ˜¯å¦å¯ç”¨Fancyboxå›¾ç‰‡ç¯ç®±æ•ˆæœ.
show_category_count: true ## æ˜¯å¦æ˜¾ç¤ºä¾§è¾¹æ åˆ†ç±»æ•°ç›®If you want to show the count of categories in the sidebar widget please set the value to true.
toc_number: false ## æ˜¯å¦æ˜¾ç¤ºæ–‡ç« ä¸­ç›®å½•åˆ—è¡¨è‡ªåŠ¨ç¼–å· If you want to add list number to toc please set the value to true.
shareto: true ## æ˜¯å¦ä½¿ç”¨åˆ†äº«æŒ‰éˆ•ï¼Œéœ€è¦å®‰è£…hexo-helper-qrcodeæ’ä»¶ä½¿ç”¨ If you want to use the share button please set the value to true, and you must have hexo-helper-qrcode installed.
wordcount: true ## æ˜¯å¦å¼€å¯æ–‡ç« ç´«è–¯å’Œé˜…è¯»æ—¶é—´ç»Ÿè®¡ï¼Œè¦å®‰è£…hexo-wordcountæ’ä»¶  If you want to display the word counter and the reading time expected to spend of each post please set the value to true, and you must have hexo-wordcount installed.
widgets_on_small_screens: true ##  æ˜¯å¦åœ¨ç§»åŠ¨è®¾å¤‡å±å¹•åº•éƒ¨æ˜¾ç¤ºä¾§è¾¹æ  Set to true to enable widgets on small screens.
canvas_nest: ## æ˜¯å¦ä½¿ç”¨canvasåŠ¨æ€èƒŒæ™¯
    enable: false ## If you want to use dynamic background please set the value to true, you can also fill the following parameters to customize the dynamic effect, or just leave them blank to keep the default effect.
    color: ## RGB value of the color, e.g. "100,99,98"
    opacity: ## Transparency of lines, e.g. "0.7"
    zIndex: ## The z-index property of the background, e.g. "-1"
    count: ## Quantity of lines, e.g. "150"
donate: ## æ˜¯å¦å¯ç”¨æèµ æŒ‰é’®
    enable: false ## If you want to display the donate button after each post, please set the value to true and fill the following items on your need. You can also enable donate button in a page by adding a "donate: true" item to the front-matter.
    github: ## GitHub URL, e.g. https://github.com/Kaiyuan/donate-page
    alipay_qr: ## Path of Alipay QRcode image, e.g. /img/AliPayQR.png
    wechat_qr: ## Path of Wechat QRcode image, e.g. /img/WeChatQR.png
    btc_qr: ## Path of Bitcoin QRcode image, e.g. /img/BTCQR.png
    btc_key: ## Bitcoin key, e.g. 1KuK5eK2BLsqpsFVXXSBG5wbSAwZVadt6L
    paypal_url: ## Paypal URL, e.g. https://www.paypal.me/tufu9441
blogtimer: true ##è®¡æ—¶å™¨

# æ–‡ç« ç»“å°¾ç‰ˆæƒä¿¡æ¯
post_copyright: ## æ˜¯å¦å±•ç¤ºç‰ˆæƒä¿¡æ¯
    enable: true ## If you want to display the copyright info after each post, please set the value to true and fill the following items on your need.
    author: ScarSu ## Your author name, e.g. tufu9441
    copyright_text: è½¬è½½éœ€ç½²å-éå•†ä¸šæ€§ä½¿ç”¨ 3.0 æœªæœ¬åœ°åŒ–ç‰ˆæœ¬ (CC BY-NC 3.0) ## Your copyright text, e.g. The author owns the copyright, please indicate the source reproduced.
    licenses_link: https://creativecommons.org/licenses/by-nc/3.0/ ## Your licenses link

# è‡ªå®šä¹‰é¡µé¢åŠèœå•
## è‡ªå®šä¹‰é¡µé¢åŠèœå•ï¼Œä¾ç…§å·²æœ‰æ ¼å¼å¡«å†™ã€‚
## å¡«å†™åè¯·åœ¨sourceç›®å½•ä¸‹å»ºç«‹ç›¸åº”åç§°çš„æ–‡ä»¶å¤¹ï¼Œå¹¶åŒ…å«index.mdæ–‡ä»¶ï¼Œä»¥æ­£ç¡®æ˜¾ç¤ºé¡µé¢ã€‚
## å¯¼èˆªèœå•ä¸­é›†æˆäº†FontAwesomeå›¾æ ‡å­—ä½“ï¼Œå¯ä»¥åœ¨è¿™é‡Œé€‰æ‹©æ–°çš„å›¾æ ‡ï¼Œå¹¶æŒ‰ç…§ç›¸å…³è¯´æ˜ä½¿ç”¨ã€‚
menu:
    - page: home
      directory: .
    - page: archive
      directory: archives/
    # - page: GitBook
    #   directory: gitbook/
    #   icon: fa-book
    - page: cognition
      directory: cognition/
    - page: friends
      directory: friends/
    - page: fe_nav
      directory: fe_nav/
    # - page: Demo
    #   directory: demo/
    #   icon: fa-code
    - page: about
      directory: about/
    - page: apps
      directory: apps/
    # - page: comment
    #   directory: comment/
    # - page: self_regulation
    #   directory: self_regulation/
    #   icon: fa-check-square-o
    - page: rss
      directory: atom.xml
      # icon: fa-rss

# Widget : Sidebar tool é€‰æ‹©å’Œæ’åˆ—å¸Œæœ›ä½¿ç”¨çš„ä¾§è¾¹æ å°å·¥å…·
## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
widgets:
    # - search
    - category
    # - tag
    # - recent_posts
    # - recent_comments
    # - links

# relative links å‹æƒ…é“¾æ¥
links:
    # - title: é½èˆå›¢
    #   url: https://75team.com/
    # - title: FEX
    #   url: http://fex.baidu.com/
    # - title: å‰ä»»Blog
    #   url: http://www.cnblogs.com/ScarSu/

# ç½‘ç«™å†å²æ—¶é—´çº¿
## åœ¨é¡µé¢front-matterï¼ˆscaffoldsï¼‰ä¸­è®¾ç½®layout: timelineå¯æ˜¾ç¤º
timeline:
    - num: 1
      word: 2014/06/12-Start
    - num: 2
      word: 2014/11/29-XXX
    - num: 3
      word: 2015/02/18-DDD
    - num: 4
      word: More

# Static files é™æ€æ–‡ä»¶å­˜å‚¨è·¯å¾„ï¼Œæ–¹ä¾¿è®¾ç½®CDNç¼“å­˜ã€‚
js: js
css: css

# Theme version ä¸»é¢˜ç‰ˆæœ¬ï¼Œä¾¿äºé™æ€æ–‡ä»¶æ›´æ–°ååˆ·æ–°CDNç¼“å­˜ã€‚
version: 0.0.0

# è‡ªå®šä¹‰head link
headLinks:
    - title: GitHub
      url: https://github.com/scarsu
      icon: fa-github
    # - title: å›½å†…é•œåƒç«™scarsu.cn
    #   url: http://www.scarsu.cn
    #   icon: fa-paper-plane
    # - title: å›½å¤–é•œåƒç«™scarsu.com
    #   url: http://www.scarsu.com
    #   icon: fa-paper-plane
    # - title: GitBook
    #   url: https://doc.scarsu.com
    #   icon: fa-book

date_format: YYYY-MM-DD

# é¦–é¡µå¼€å¯ç”»å»Šæ¨¡å¼
gallery: true

# æ–‡ç« çŠ¶æ€
status: 
  Done: 
    content: âœ…
  Work in Progress: 
    content: ğŸš§
  Draft: 
    content: â­•
  Continuous Updates: 
    content: ğŸ”„